source('helpers_v2.R')
source('prepare_data.R')

## Скрипт для проверки на 5 записях
df1 <- prepareData(cd_file = '../../data/tmp/0_cd_file_small.xlsx',
                   bank = 'BBKK',
                   balance_file = '../../data/tmp/1_balance_file_small.csv',
                   binbonus_file = '../../data/tmp/2_binbonus_file_small.csv',
                   limit_file = '../../data/tmp/3_limit_file_small.csv',
                   sd_file = '../../data/tmp/4_sd_file_small.xlsx',
                   NA_percent = 1,
                   one_col_max_percent = 1.5,
                   status_file = '../../data/tmp/5_status_file_small.csv',
                   st_top_n_cols = list(), ## c('name' = 'CONTR_STATUS', 'percentage' = 0.99)
                   code_maps_card_rds = '', code_maps_contr_rds = '',
                   addr_file = '../../data/tmp/6_addr_file_small.csv',
                   addr_top_n_cols = list(),
                   addr_code_maps_rds = '',
                   phone_file = '../../data/tmp/7_phone_file_small.csv',
                   transactions_file = '../../data/tmp/8_transaction_file_small.csv',
                   mcc_file = '../../data/mcc.csv',
                   trns_agg_window = 45,
                   trns_n_recent = 20,
                   trns_top_n_cols = list(),
                   trns_agg_cols = list('TXN_RUB_AMT',
                                        c(7, 31, 90, 180),
                                        c('TXN_TP', 'TXN_CHN', 'CODE'),
                                        funs(MEAN = mean, MAX = max, N = length, SUM = sum)),
                   trns_code_maps_rds = '',
                   output_dir = './BBKK_tmp',
                   verbose = TRUE)



## Скрипт для создания обучающей выборки
df1 <- prepareData(cd_file = '../../data/dataset_debts/2018-02-19 train_bbkk_tmp.xlsx',
                   bank = 'BBKK',
                   balance_file = '../../data/dataset_debts/BALANCE/модель_часть_2_балансы_ББКК_изменения.csv',
                   binbonus_file = '../../data/dataset_debts/2017-06-29 Binbonus_client_history_BBKK.csv',
                   limit_file = '../../data/dataset_debts/LIMIT/ББКК_лимиты.csv',
                   sd_file = '../../data/dataset_debts/soc_dem.xlsx',
                   NA_percent = 1,
                   one_col_max_percent = 1,
                   status_file = '../../data/dataset_debts/2017-06-29 debt_bbkk.csv',
                   st_top_n_cols = list(),
                   code_maps_card_rds = '', code_maps_contr_rds = '',
                   addr_file = '../../data/dataset_debts/addr_new1.csv',
                   addr_top_n_cols = list(),
                   addr_code_maps_rds = '',
                   phone_file = '../../data/dataset_debts/2017-06-28_phone_bbkk.csv',
                   transactions_file = '../../data/dataset_debts/DATASET_TXN/DATASET_TXN_BBKK.csv',
                   mcc_file = '../../data/mcc.csv',
                   trns_agg_window = 45,
                   trns_n_recent = 20,
                   trns_top_n_cols = list(),
                   trns_agg_cols = list('TXN_RUB_AMT',
                                        c(7, 31, 90, 180),
                                        c('TXN_TP', 'TXN_CHN', 'CODE'),
                                        funs(MEAN = mean, MAX = max, N = length, SUM = sum)),
                   trns_code_maps_rds = '',
                   output_dir = './BBKK_train_new2',
                   verbose = TRUE)

## Скрипт для создания тестовой выборки
data_folder <- "DATASET_MCV 26.04.2018"

df1 <- prepareData(cd_file = paste0("../",glue("{data_folder}/MICR_SMV_BASE.xlsx")),
                   bank = 'BBKK',
                   balance_file = paste0("../",glue("{data_folder}/MICR_SMV_BALANCE.csv")),
                   binbonus_file = paste0("../",glue("{data_folder}/MICR_SMV_BINBONUS_1.csv")),
                   limit_file = paste0("../",glue("{data_folder}/MICR_SMV_LIM.csv")),
                   sd_file = paste0("../",glue("{data_folder}/MICR_SMV_IQ_SD.xlsx")),
                   NA_percent = 1,
                   one_col_max_percent = 1,
                   status_file = paste0("../",glue("{data_folder}/MICR_SMV_STATUS.csv")),
                   st_top_n_cols = list('CONTR_STATUS'),
                   code_maps_card_rds = paste0("../",glue("{data_folder}/ST_CARD_2018-02-19.rds")),
                   code_maps_contr_rds = paste0("../",glue("{data_folder}/ST_CONTR_2018-02-19.rds")),
                   addr_file =  paste0("../",glue("{data_folder}/MICR_SMV_IQ_ADDR_ALL.csv")),
                   addr_top_n_cols = list(),
                   addr_code_maps_rds =  paste0("../",glue("{data_folder}/ADDR_2018-02-19.rds")),
                   phone_file =  paste0("../",glue("{data_folder}/MICR_SMV_PHONE.csv")),
                   transactions_file = paste0("../",glue("{data_folder}/MICR_SMV_TXN.csv")),
                   mcc_file = paste0("../",glue("{data_folder}/mcc_v2.csv")),
                   trns_agg_window = 45,
                   trns_n_recent = 20,
                   trns_top_n_cols = list(),
                   trns_agg_cols = list('TXN_RUB_AMT',
                                        c(7, 31, 90, 180),
                                        c('TXN_TP', 'TXN_CHN', 'CODE'),
                                        funs(MEAN = mean, MAX = max, N = length, SUM = sum)),
                   trns_code_maps_rds = paste0("../",glue("{data_folder}/TRNS_2018-02-19.rds")),
                   output_dir = '../test2_05_2018',
                   verbose = TRUE)
