source('helpers.R')
source('prepare_data.R')

## for training bb ----
df1 <- prepareData(cd_file = '../../data/dataset_debts/2017-06-29 POS_ATM_SC_CD.xlsx',
                   bank = 'BinBank',
                   balance_file = '../../data/dataset_debts/BALANCE/модель_часть_2_балансы_ББ_изменения.csv',
                   binbonus_file = '../../data/dataset_debts/2017-06-29 Binbonus_client_history_Binbank.csv',
                   limit_file = '../../data/dataset_debts/LIMIT/ББ_лимиты.csv',
                   sd_file = '../../data/dataset_debts/soc_dem.xlsx',
                   NA_percent = 0.7,
                   one_col_max_percent = 0.95,
                   status_file = '../../data/dataset_debts/2017-06-29 debt_bk.csv',
                   st_top_n_cols = list(c('name' = 'CONTR_STATUS', 'percentage' = 0.9)),
                   code_maps_card_rds = '', code_maps_contr_rds = '',
                   addr_file = '../../data/dataset_debts/addr_new1.csv',
                   addr_top_n_cols = list(c(name = 'AddrCity2', percentage = 0.55),
                                          c(name = 'AddrCountry', percentage = 0.99)),
                   addr_code_maps_rds = '',
                   phone_file = '../../data/dataset_debts/2017-06-28_phone_bk.csv',
                   transactions_file = '../../data/dataset_debts/DATASET_TXN/DATASET_TXN_BB.csv',
                   mcc_file = '../../bnb/bnk/data/model/mcc.csv', 
                   trns_agg_window = 45,
                   trns_n_recent = 20,
                   trns_top_n_cols = list(c('name' = 'CODE', 'percentage' = 0.9),
                                          c('name' = 'TXN_CHN', 'percentage' = 0.9),
                                          c('name' = 'TXN_CTR', 'percentage' = 0.9)),
                   trns_agg_cols = list('TXN_RUB_AMT',
                                        c(7, 31, 90, 180), 
                                        c('TXN_TP', 'TXN_CHN', 'CODE'),
                                        funs(MEAN = mean, MAX = max, N = length, SUM = sum)),
                   trns_code_maps_rds = '',
                   output_dir = './BB',
                   verbose = TRUE)

## test bb (columns missing in cd-file, recover code_maps) ----
df1 <- prepareData(cd_file = '../../data/dataset_debts/CD_TEST.xlsx',
                   bank = 'BinBank',
                   balance_file = '../../data/dataset_debts/BALANCE/модель_часть_2_балансы_ББ_изменения.csv',
                   binbonus_file = '../../data/dataset_debts/2017-06-29 Binbonus_client_history_Binbank.csv',
                   limit_file = '../../data/dataset_debts/LIMIT/ББ_лимиты.csv',
                   sd_file = '../../data/dataset_debts/soc_dem.xlsx',
                   NA_percent = 0.7,
                   one_col_max_percent = 0.95,
                   status_file = '../../data/dataset_debts/2017-06-29 debt_bk.csv',
                   st_top_n_cols = list(c('name' = 'CONTR_STATUS', 'percentage' = 0.9)),
                   code_maps_card_rds = 'BB/ST_CARD_2017-07-05.rds',
                   code_maps_contr_rds = 'BB/ST_CONTR_2017-07-05.rds',
                   addr_file = '../../data/dataset_debts/addr_new1.csv',
                   addr_top_n_cols = list(c(name = 'AddrCity2', percentage = 0.55),
                                          c(name = 'AddrCountry', percentage = 0.99)),
                   addr_code_maps_rds = '',
                   phone_file = '../../data/dataset_debts/2017-06-28_phone_bk.csv',
                   transactions_file = '../../data/dataset_debts/DATASET_TXN/DATASET_TXN_BB.csv',
                   mcc_file = '../../bnb/bnk/data/model/mcc.csv', 
                   trns_agg_window = 45,
                   trns_n_recent = 20,
                   trns_top_n_cols = list(c('name' = 'CODE', 'percentage' = 0.9),
                                          c('name' = 'TXN_CHN', 'percentage' = 0.9),
                                          c('name' = 'TXN_CTR', 'percentage' = 0.9)),
                   trns_agg_cols = list('TXN_RUB_AMT',
                                        c(7, 31, 90, 180), 
                                        c('TXN_TP', 'TXN_CHN', 'CODE'),
                                        funs(MEAN = mean, MAX = max, N = length, SUM = sum)),
                   trns_code_maps_rds = 'BB/TRNS_2017-07-05.rds',
                   output_dir = './BB_TEST',
                   verbose = TRUE)

## no top-N cols bb----
df1 <- prepareData(cd_file = '../../data/dataset_debts/2017-06-29 POS_ATM_SC_CD.xlsx',
                   bank = 'BinBank',
                   balance_file = '../../data/dataset_debts/BALANCE/модель_часть_2_балансы_ББ_изменения.csv',
                   binbonus_file = '../../data/dataset_debts/2017-06-29 Binbonus_client_history_Binbank.csv',
                   limit_file = '../../data/dataset_debts/LIMIT/ББ_лимиты.csv',
                   sd_file = '../../data/dataset_debts/soc_dem.xlsx',
                   NA_percent = 0.7,
                   one_col_max_percent = 0.95,
                   status_file = '../../data/dataset_debts/2017-06-29 debt_bk.csv',
                   st_top_n_cols = list(),#c('name' = 'CONTR_STATUS', 'percentage' = 0.9)),
                   code_maps_card_rds = '', code_maps_contr_rds = '',
                   addr_file = '../../data/dataset_debts/addr_new1.csv',
                   addr_top_n_cols = list(),#c(name = 'AddrCity2', percentage = 0.55),
                   #c(name = 'AddrCountry', percentage = 0.99)),
                   addr_code_maps_rds = '',
                   phone_file = '../../data/dataset_debts/2017-06-28_phone_bk.csv',
                   transactions_file = '../../data/dataset_debts/DATASET_TXN/DATASET_TXN_BB.csv',
                   mcc_file = '../../bnb/bnk/data/model/mcc.csv', 
                   trns_agg_window = 45,
                   trns_n_recent = 20,
                   trns_top_n_cols = list(),#c('name' = 'CODE', 'percentage' = 0.9),
                   #c('name' = 'TXN_CHN', 'percentage' = 0.9),
                   #c('name' = 'TXN_CTR', 'percentage' = 0.9)),
                   trns_agg_cols = list('TXN_RUB_AMT',
                                        c(7, 31, 90, 180), 
                                        c('TXN_TP', 'TXN_CHN'),
                                        funs(MEAN = mean, MAX = max, N = length, SUM = sum)),
                   trns_code_maps_rds = '',
                   output_dir = './BB',
                   verbose = TRUE)

## bbkk train ----
df1 <- prepareData(cd_file = '../../data/dataset_debts/2017-06-29 POS_ATM_SC_CD.xlsx',
                   bank = 'BBKK',
                   balance_file = '../../data/dataset_debts/BALANCE/модель_часть_2_балансы_ББКК_изменения.csv',
                   binbonus_file = '../../data/dataset_debts/2017-06-29 Binbonus_client_history_BBKK.csv',
                   limit_file = '../../data/dataset_debts/LIMIT/ББКК_лимиты.csv',
                   sd_file = '../../data/dataset_debts/soc_dem.xlsx',
                   NA_percent = 0.7,
                   one_col_max_percent = 0.95,
                   status_file = '../../data/dataset_debts/2017-06-29 debt_bbkk.csv',
                   st_top_n_cols = list(c('name' = 'CONTR_STATUS', 'percentage' = 0.9)),
                   code_maps_card_rds = '', code_maps_contr_rds = '',
                   addr_file = '../../data/dataset_debts/addr_new1.csv',
                   addr_top_n_cols = list(c(name = 'AddrCity2', percentage = 0.55),
                                          c(name = 'AddrCountry', percentage = 0.99)),
                   addr_code_maps_rds = '',
                   phone_file = '../../data/dataset_debts/2017-06-28_phone_bbkk.csv',
                   transactions_file = '../../data/dataset_debts/DATASET_TXN/DATASET_TXN_BBKK.csv',
                   mcc_file = '../../bnb/bnk/data/model/mcc.csv', 
                   trns_agg_window = 45,
                   trns_n_recent = 20,
                   trns_top_n_cols = list(c('name' = 'CODE', 'percentage' = 0.9),
                                          c('name' = 'TXN_CHN', 'percentage' = 0.9),
                                          c('name' = 'TXN_CTR', 'percentage' = 0.9)),
                   trns_agg_cols = list('TXN_RUB_AMT',
                                        c(7, 31, 90, 180), 
                                        c('TXN_TP', 'TXN_CHN', 'CODE'),
                                        funs(MEAN = mean, MAX = max, N = length, SUM = sum)),
                   trns_code_maps_rds = '',
                   output_dir = './BBKK',
                   verbose = TRUE)

## no top-N cols BBKK ----
df1 <- prepareData(cd_file = '../../data/dataset_debts/2017-06-29 POS_ATM_SC_CD.xlsx',
                   bank = 'BBKK',
                   balance_file = '../../data/dataset_debts/BALANCE/модель_часть_2_балансы_ББКК_изменения.csv',
                   binbonus_file = '../../data/dataset_debts/2017-06-29 Binbonus_client_history_BBKK.csv',
                   limit_file = '../../data/dataset_debts/LIMIT/ББКК_лимиты.csv',
                   sd_file = '../../data/dataset_debts/soc_dem.xlsx',
                   NA_percent = 0.7,
                   one_col_max_percent = 0.95,
                   status_file = '../../data/dataset_debts/2017-06-29 debt_bbkk.csv',
                   st_top_n_cols = list(),
                   code_maps_card_rds = '', code_maps_contr_rds = '',
                   addr_file = '../../data/dataset_debts/addr_new1.csv',
                   addr_top_n_cols = list(),
                   addr_code_maps_rds = '',
                   phone_file = '../../data/dataset_debts/2017-06-28_phone_bbkk.csv',
                   transactions_file = '../../data/dataset_debts/DATASET_TXN/DATASET_TXN_BBKK.csv',
                   mcc_file = '../../bnb/bnk/data/model/mcc.csv', 
                   trns_agg_window = 45,
                   trns_n_recent = 20,
                   trns_top_n_cols = list(),
                   trns_agg_cols = list('TXN_RUB_AMT',
                                        c(7, 31, 90, 180), 
                                        c('TXN_TP', 'TXN_CHN', 'CODE'),
                                        funs(MEAN = mean, MAX = max, N = length, SUM = sum)),
                   trns_code_maps_rds = '',
                   output_dir = './BBKK',
                   verbose = FALSE)
